# -*- mode: python ; coding: utf-8 -*-
from pathlib import Path

datas = [
    ('modes', 'modes'),
    ('app/ui/styles', 'app/ui/styles'),
    ('DEDICATED_MODES', 'DEDICATED_MODES'),
    ('assets', 'assets'),
]


hiddenimports = [
    'app',
    'app.actions',
    'app.actions.audio',
    'app.actions.base',
    'app.actions.browser',
    'app.actions.conditional',
    'app.actions.filesystem',
    'app.actions.keyboard',
    'app.actions.midi',
    'app.actions.mouse',
    'app.actions.notification',
    'app.actions.process',
    'app.actions.wait',
    'app.actions.windows',
    'app.core',
    'app.core.action_registry',
    'app.core.automation_engine',
    'app.core.event_bus',
    'app.core.exceptions',
    'app.core.execution_context',
    'app.core.mode_manager',
    'app.integrations',
    'app.integrations.base',
    'app.integrations.discord',
    'app.integrations.fl_studio',
    'app.integrations.spotify',
    'app.integrations.steam',
    'app.models',
    'app.models.action',
    'app.models.action_result',
    'app.models.device',
    'app.models.mode',
    'app.models.settings',
    'app.persistence',
    'app.persistence.database',
    'app.persistence.json_store',
    'app.persistence.settings_store',
    'app.services',
    'app.services.device_service',
    'app.services.hotkey_service',
    'app.services.icon_service',
    'app.services.notification_service',
    'app.services.startup_service',
    'app.ui',
    'app.ui.action_editor',
    'app.ui.animation_manager',
    'app.ui.command_palette',
    'app.ui.overlay',
    'app.ui.toast',
    'app.ui.smooth_scroll',
    'app.ui.smooth_stacked',
    'app.ui.dashboard',
    'app.ui.device_panel',
    'app.ui.execution_dialog',
    'app.ui.logs_panel',
    'app.ui.main_window',
    'app.ui.mode_editor',
    'app.ui.settings',
    'app.ui.design',
    'app.ui.design.tokens',
    'app.ui.design.theme',
    'app.ui.widgets',
    'app.ui.widgets.action_row',
    'app.ui.widgets.app_picker_dialog',
    'app.ui.widgets.hotkey_input',
    'app.ui.widgets.mode_card',
    'app.ui.widgets.sidebar',
    'app.ui.widgets.status_indicator',
    'app.windows',
    'app.windows.audio',
    'app.windows.devices',
    'app.windows.hotkeys',
    'app.windows.processes',
    'app.windows.windows',
    'psutil',
    'win32con',
    'win32gui',
    'win32process',
    'win32api',
    'pydantic',
    'PySide6',
    'PySide6.QtCore',
    'PySide6.QtGui',
    'PySide6.QtWidgets',
    'PySide6.QtNetwork',
    'win32com',
    'win32com.client',
]

a = Analysis(
    ['run.py'],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tkinter', 'unittest', 'pydoc'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='AutomationHub',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/app_icon.ico',
    version='version_info.txt',
)

